### ISSUE TITLE
Cannot load the plugin

### ISSUE THREAD

**Issue by billsu077783** [janniks/vue-notion#104]
**Either` import `or `Vue.use` `Vue.component`, the following error occurs:**

    Module parse failed: Unexpected token (283:11)
    You may need an appropriate loader to handle this file type.
    |   extends: Blockable,
    |   name: "NotionDecorator",
    |   props: { ...blockProps,
    |     content: Array
    |   },

**please help, thanks**

**Comment by janniks** [comment]
Please try to update to version >=`1.5.1` and check if that solves the problem
