### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by manuelvargastapia** [janniks/vue-notion#14]
It's possible to use a dark theme? I want to switch between light and dark theme on my page, but NotionRenderer doesn't seem to consider such a thing.

I'm importing the default style from /src/styles.css. I was considering overriding some of the attributes but I don't find a way to make the switch in runtime (maybe [SASS conditional variables](https://sass-lang.com/documentation/at-rules/control/if) could work, but they are evaluated compile time. Furthermore, [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) doesn't work either because I don't have access to the component to include new classes).

Is there any workaround? Am I missing something (consider that I'm new to Vue and web development in general)?

-------

Btw, I'd like to thank you for building this tool. I was messing around with Nuxt and Content to build my blog, but after a while, I found this library, and did the process a lot easier! Thanks!

**Comment by janniks** [comment]
Unfortunately not yet.

I will try to add this soon...

For now, the only way that I can think of is adding overriding styles that are only activated in "dark mode" (e.g. `body.dark .notion { ... }` adding the `dark` class to body when dark mode is activated).

**Comment by rylax** [comment]
> Unfortunately not yet.
> 
> I will try to add this soon...
> 
> For now, the only way that I can think of is adding overriding styles that are only activated in "dark mode" (e.g. `body.dark .notion { ... }` and adding the `dark` class to body when dark mode is activated).

Agree, I used the exact same technique for my [blog](https://dominiksobe.com) and it _just_ works. I am using tailwind css and combined it with https://tailwindcss.com/docs/dark-mode which made it even easier.

**Comment by janniks** [comment]
We'll likely not add dark mode support, unless Notion adds it as well.

Dark mode can easily be added via custom CSS, as mentioned by @rylax
