### ISSUE TITLE
Use blocks in Nuxt layouts and components

### ISSUE THREAD

**Issue by seanherron** [janniks/vue-notion#18]
Hi there,

First off - _thank you_! I'm loving playing around with `vue-notion`.

I'm experimenting with using Notion pages as components in my Nuxt project (I copied the Nuxt example from this repo). In this case, I have a Notion page called "header" that contains the information I want in my header, and a page called "footer" that I want to use as my footer. 

I modified `layouts/default.vue` to contain references to my `Header` component:

```
<template>
  <div>
    <Header />
    <Nuxt />
  </div>
</template>
```

I also created `components/Header.vue`:

```
<template>
  <div>
    <NotionRenderer :blockMap="headerMap" />
  </div>
</template>

<script>
export default {
  data: () => ({ headerMap: null }),
  async asyncData({ $notion, params, error }) {
    const headerMap = await $notion.getPageBlocks("#####");

    return {
      headerMap
    };
  },
};
</script>
```

Unfortunantely, it doesn't seem to render the blocks from my Notion page in the page. If I add static HTML strings (eg. `<h1>Hello!</h1>`) in to my component template, it _does_ render - so I'm guessing I'm missing something with how vue-notion should be initialized outside of the page construct?

**Comment by janniks** [comment]
Hi 👋🏻

Everything looks okay at first glance — it should work as a component just as well as a page...

Are there any error messages in your terminal or browser console? It would also help if you could share the header page — maybe the used block types aren't implemented yet.

**Comment by seanherron** [comment]
Yeah - thanks for the CodeSandbox suggestion! The issue can be replicated here:

https://codesandbox.io/s/vue-notion-component-example-tkfy7?file=/components/Header.vue

The Notion pages sourcing the example are linked in the files - it's just plain text blocks.

**Comment by janniks** [comment]
I think you might be right regarding pages being the issue.

https://nuxtjs.org/docs/2.x/features/data-fetching/ in Nuxt it looks like the `asyncData` hook only exists on pages (not components). Maybe try replacing this with the `fetch` hook.

**Comment by seanherron** [comment]
Yeah - I was hoping since a page inherits the component it would work, but I guess not.

Playing around with `fetch` and I'm not seeing a ton of success - eg.
```export default {
  data: () => ({ headerMap: null }),
  async fetch({ $notion, params, error }) {
    const headerMap = await fetch(
      $notion.getPageBlocks("a6cd6473622d49af957b242c827ca461")
    );
  },
};```

Has the same result. Will try some more on this tomorrow - in the meantime I'll probably just statically write my header and footer content. Thanks for the quick assist!

**Comment by janniks** [comment]
Looks like I got it working with a minor change: https://codesandbox.io/s/vue-notion-component-example-forked-cr0ug?file=/components/Header.vue

The [fetch hook](https://nuxtjs.org/docs/2.x/components-glossary/pages-fetch) doesn't offer `context` directly, but we can access it via `this.$nuxt.context`. Additionally, we have to set the `blockMap` via `this.headerMap =` rather than `return { headerMap }`.

Hope it helps! ☀️ Let me know if there is anything else you need
