### ISSUE TITLE
editor

### ISSUE THREAD

**Issue by dudif91** [janniks/vue-notion#19]
Hi,
is there a way to edit the content with this package? or maybe to get a like notion editor?

**Comment by janniks** [comment]
Hi 👋🏻

Thanks for the interest!

Unfortunately, no — vue-notion will probably not integrate editing features in the future either. An editor would be awesome, but is difficult to implement via the current private API. Also, this package and the bundled API wrappers are better used in a static-build fashion.

I hope that answers your question 🙋🏼‍♂️
