### ISSUE TITLE
Not found the class of text & background color

### ISSUE THREAD

**Issue by rintaki** [janniks/vue-notion#20]
Hi, thanks to open this cool project so much!
Btw, is the class activate such as text-color and background-color now?

**Comment by janniks** [comment]
Hi 👋🏻

I'm not quite sure what you mean — can you provide an example with any potential errors?

**Comment by rintaki** [comment]
Sorry, when I checked again, there is no problem about the class of color🙏
It's better to add `span` to the text-color in vue-notion/src/styles.css. 
Like this
```
.notion-gray {
  color: rgb(155, 154, 151);
}
```
↓
```
.notion-gray span{
  color: rgb(155, 154, 151);
}
```

**Comment by janniks** [comment]
Interesting. Why is that?

For which blocks does it make a difference? Happy to change this if there is a better solution.

**Comment by janniks** [comment]
We are trying to stay as close as possible to the original styles of [`react-notion`](https://github.com/splitbee/react-notion/blob/master/src/styles.css), so I'm going to leave this as is, for now...

Thanks for the report! ☀️
