### ISSUE TITLE
Vue 3 compatibility

### ISSUE THREAD

**Issue by bahadirhanfiliz** [janniks/vue-notion#24]
Hello, first of all thank you for this open source project. It looks really nice!

I am using vue3 without Nuxt and probably having issues related to installation.

1- I have installed packages from NPM vue-notion and prismjs
2- I have imported them in my main.js file.
3- I have used the example code template. But received errors that I am sharing.

Dependencies:
```
"dependencies": {
    "aws-amplify": "^3.3.25",
    "core-js": "^3.6.5",
    "firebase": "^8.3.1",
    "primevue": "^3.3.5",
    "prismjs": "^1.23.0",
    "vue": "^3.0.0",
    "vue-notion": "^0.3.2",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
  }
```

main.js
```
import NotionVue from 'vue-notion'
import PrismJS from 'prismjs'

createApp(App).use(store).use(NotionVue).use(PrismJS).use(router).use(PrimeVue).mount('#app')
```

Errors from console
![image](https://user-images.githubusercontent.com/46743449/112753940-7c8e1800-8fe2-11eb-8c83-31823e8b9df9.png)

Is this package compatible with Vue3 without using Nuxt? If it is can you share more detailed steps for installation?

**Comment by janniks** [comment]
Hi 👋🏻 thanks for checking out vue-notion.

Unfortunately, we don't have a Vue 3 compatible release yet. I might be able to look into it in the next few days.

**Comment by bahadirhanfiliz** [comment]
Hello, thanks for the fast return. I think it would be a good feature for the community as well. Thanks for all your efforts!

**Comment by janniks** [comment]
After some minor research it might actually already work in Vue 3. I can do some tests later.

It won't work with the `.use` method of Vue, because vue-notion isn't a plugin. However, you should be able to import and use the components as shown in the vue-notion examples.

**Comment by bahadirhanfiliz** [comment]
I have tried without using `.use` method, but it doesn't work, fyi. Moreover, I needed to use `npm install vue-notion --legacy-peer-deps` while installing. Since I get an error like this:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/46743449/112756219-ddbae900-8fec-11eb-8dbb-8b5ead28e3d5.png">

Hope it helps,

**Comment by bahadirhanfiliz** [comment]
Hi @janniks ,

Hope you doing well. Have you done any tests? If it works for vue3 already, I would love to use it :)

**Comment by janniks** [comment]
Hey, sorry for the delay — I tested with a fresh Vue 3 project and it seems like it's NOT compatible yet.
I will try to port a Vue 3 version and release some time next week.

**Comment by janniks** [comment]
#38 Vote here for Vue 3 support — will close for now...
