### ISSUE TITLE
Notion supports each user subdomain.

### ISSUE THREAD

**Issue by quroom** [janniks/vue-notion#36]
So vue-notion doesn't work anymore with notion link with subdomain.

**Comment by janniks** [comment]
Hi 👋🏻 Thanks for using vue-notion. I'm not quite sure what you mean. Can you provide a notion page id or a codesandbox example?

**Comment by quroom** [comment]
Before leave codesandbox example, I leave the link behavior changes https://www.notion.so/blog/personalize-public-pages
I will leave codesandbox :)

**Comment by quroom** [comment]
As you can check real notion page which is not rendered by vue-notion.
https://www.notion.so/FAQ-ee73db868234432497d7616454ee549f#f5d96590be36443e81dc82fc7cb7e5cb
This page includes "like https://www.notion.so/onepaper/62cedd17d8634bd3af48f15db63b2b5c" back link.
But this back link is not shown in vue-notion

I leave codesandbox link for testing new notion url system.
https://codesandbox.io/s/vue-notion-component-example-forked-1990z?file=/pages/index.vue

**Comment by janniks** [comment]
I looked into this for a while. I'm not quite sure what's happening, but it looks like the links don't even show up in the response from https://github.com/splitbee/notion-api-worker — we will have to wait until they implement this feature. I'm sorry

**Comment by quroom** [comment]
No problem.
Have a nice day
