### ISSUE TITLE
Add Vue 3 Support? 👀

### ISSUE THREAD

**Issue by janniks** [janniks/vue-notion#38]
Hi `vue-notion` users!

I am thinking about adding support for Vue 3. However, due to tooling and API differences this will be quite complicated. It will likely have to live in its own repo or branch. Also Vue 3 will not be usable with Nuxt, until Nuxt 3 is released.

As soon as Nuxt 3 is released, I will definitely migrate this repo to Vue 3.

Think of this issue as a poll:
- ~Vote ♥️ : Add Vue 3 support as its own version (e.g. `vue-notion@vue3-0.1.0`)~
- ~Vote 👀 : Wait until Nuxt is compatible with Vue 3~

**EDIT:**
As Vue 3 is now the next hot+stable thing, I'll introduce the Vue 3 compatible version as >= 3.0.0 _(skipping 2.0.0)_ — hopefully soon.... Nuxt 3 isn't quite out yet, but I'll try to make it work 🤷‍♀

**Comment by CalebKester** [comment]
@janniks just wondering what the status on this is. With Nuxt3 coming out as well as Vue3 with Vite, what do you think about making this a composable for vue3 so it could also be used regardless of vue3 framework?

**Comment by yacosta738** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/c1ce9c0a-a16e-4d00-a3e1-049b89d14f03-db1ffc10-9e7f-4bea-a043-e744f59d5043-v1.png?transparent=1&palette=1&width=246)

**Comment by paulocastellano** [comment]
What's the status of it?

**Comment by rashidpathiyil** [comment]
I want use notion with Nuxt 3.
Please share if you have information that help.

**Comment by janniks** [comment]
Looks like Vue 3 is the new standard at this point, so I'll prioritize a switch soon. Will give a status update in two weeks (on vacation currently).

**Comment by janniks** [comment]
Opened a PR: https://github.com/janniks/vue-notion/pull/102 (still some way to go, especially on the Nuxt front)

Feel free to test the [`alpha`](https://github.com/janniks/vue-notion/pull/102) released under `3.0.0-alpha.0` (e.g. `npm i vue-notion@3.0.0-alpha.0`)

**Comment by janniks** [comment]
Sorry, for the delays — `3.0.0-alpha.1` now available, maybe this should work soon 🚀

**Comment by iBobik** [comment]
Trying to use it on Nuxt 3.

When installed it warns about `vue-dompurify-html` requiring Vue 2:

```
> npm install vue-notion@^3.0.0-alpha.1 --save-dev
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: vue-dompurify-html@2.6.0
npm WARN Found: vue@3.2.45
npm WARN node_modules/vue
npm WARN   vue@"^3.2.13" from @hsorby/vue3-katex@0.6.0-rc.4
npm WARN   node_modules/@hsorby/vue3-katex
npm WARN     @hsorby/vue3-katex@"^0.6.0-rc.4" from vue-notion@3.0.0-alpha.1
npm WARN     node_modules/vue-notion
npm WARN   9 more (@nuxt/vite-builder, @unhead/vue, @vitejs/plugin-vue, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer vue@"^2.0.0" from vue-dompurify-html@2.6.0
npm WARN node_modules/vue-dompurify-html
npm WARN   vue-dompurify-html@"^2.5.2" from @hsorby/vue3-katex@0.6.0-rc.4
npm WARN   node_modules/@hsorby/vue3-katex
npm WARN 
npm WARN Conflicting peer dependency: vue@2.7.14
```

Then after start:
```
 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'options')

  at module.exports (node_modules/vue-notion/nuxt/index.js:9:13)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6840:5)0:54:57
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
```

Also using component directly (without Nuxt module) does not work:
<img width="511" alt="Snímek obrazovky 2022-12-31 v 17 32 33" src="https://user-images.githubusercontent.com/614232/210154515-ee965982-14ba-44e1-ba71-353ad2f8b3ab.png">

**Comment by janniks** [comment]
Released `3.0.0-alpha.2`, hope that solves some of the problems 🤞

**Comment by janniks** [comment]
✨ **Vue 3 support in vue-notion is here!**

I believe `vue-notion@3.0.0-beta.1` is working, so I pushed it to main and released. Still marking as `beta` for now until the first folks try it out. 🙌

**Comment by ebanDev** [comment]
That is amazing ! :D Thank you so much

**Comment by wJoenn** [comment]
@janniks Beta's been available for more than a year now, is there anything that's preventing you from officially releasing v3 at this point ?

**Comment by janniks** [comment]
Hey @wJoenn,
Right now I'm personally considering the released version pretty much stable. The only thing holding me off was that I haven't updated the Nuxt example yet in the repo (I don't think I'll find any issues with the package in Nuxt, but that was deterring me).

But I understand the want for a cleaner/stable tag -- I'll try to get to this soon, maybe next weekend 🙌
