### ISSUE TITLE
Add Notion page links

### ISSUE THREAD

**Issue by bkane1** [janniks/vue-notion#4]
Really great project! This will be super useful for our team. 

One thing we noticed is that backlinks to other notion pages show up only as a small black triangle. 
<img width="771" alt="Screen Shot 2020-12-23 at 1 55 52 PM" src="https://user-images.githubusercontent.com/72609023/103029006-df28d100-4526-11eb-89a0-69f86c8f8d10.png">

It should look like this:
<img width="714" alt="Screen Shot 2020-12-23 at 1 56 11 PM" src="https://user-images.githubusercontent.com/72609023/103029055-f4056480-4526-11eb-9eb6-58c3908fc2dc.png">

Any ideas on how to fix that?

**Comment by janniks** [comment]
That's great to hear! Sorry for that bug – if you send me a public notion page link to reproduce it, I can look into this.

**Comment by bkane1** [comment]
@janniks sure - here is a public notion page that has that issue: https://www.notion.so/Sync-data-from-Google-Sheets-to-SQL-705a10f7f56a4c4abc2b2a7e8a2ac57f. The "Forms" backlink in the call-out at the top of the page is what's not rendering correctly. 

Thanks!

**Comment by janniks** [comment]
Adding this feature to the roadmap — will implement once this works in `react-notion`, maybe sooner

**Comment by janniks** [comment]
@bkane1 Sorry this took so long. Should be fixed in `1.1.0`

**Comment by janniks** [comment]
@quroom via https://github.com/splitbee/react-notion/issues/67 this is solved now. Please let me know if everything works out. 👍

**Comment by quroom** [comment]
@janniks Thanks for answering!
