### ISSUE TITLE
Allow embeds to use fullscreen

### ISSUE THREAD

**Issue by jedihugo** [janniks/vue-notion#41]
By default, the youtube embed disable full screen mode. Any tips on how to override this?

![image](https://user-images.githubusercontent.com/4241302/127774461-0b9e6b35-6a4c-4838-8369-eafe96e3aced.png)

**Comment by janniks** [comment]
Interesting! Have you tried with different videos? I know YouTube blocks this for some. I will look into it...

**Comment by jedihugo** [comment]
Yes, I have tried with all kind of videos.. somehow by default full screen not available

**Comment by janniks** [comment]
Got it! Trying to solve, should be fixed soon — I'll let you know here, in a few minutes.

**Comment by janniks** [comment]
Should be solved with version `1.1.1`. You can update `vue-notion` to try it out 👍 Let me know if everything works out

**Comment by jedihugo** [comment]
Everything works out great! Thank you!
