### ISSUE TITLE
Use `notion-types` and `notion-utils` packages from react-notion-x

### ISSUE THREAD

**Issue by osbre** [janniks/vue-notion#43]
I think using these packages might reduce the maintaining load of keeping up with possible new changes and types? 

https://github.com/NotionX/react-notion-x/issues/27#issuecomment-774776645

**Comment by janniks** [comment]
Great idea 💡 thanks for linking. I will have a look at them

**Comment by janniks** [comment]
_Closing for now._ I will keep this in mind, but for now it's easier to maintain a separate copy from the upstream react-notion
