### ISSUE TITLE
"Link to page" blocks do not seem to render

### ISSUE THREAD

**Issue by bramn** [janniks/vue-notion#47]
Like the title says. I am linking from one Notion page to another. For both pages the option "Share to web" are enabled. I can render them both, but the "Link to page" block is not rendering. 

I tried checking the example, but it does not seem to make use of "Link to page" block. I am assuming here that "Link to page" is the same as "Page links", which is in the table of "Supported blocks" in the README 😊

**Comment by janniks** [comment]
Hi 👋🏻 thanks for using `vue-notion`

It would help a lot if you could share the pageIds, so I can test it out.
I believe page links are a bit different (especially when they are a separate block, aka on their own row). Maybe also try "mention this page" (or similar) in Notion, to keep the link inline (this works I believe, but I will check again for you).

**Comment by bramn** [comment]
Sure, the page id I am referring to is `a73c910b26324025a955b0ae35c804de`. I am indeed using a separate page link block. When using inline links, they are rendered correctly. Although the link itself throws an error though. Which might a separate issue ☺️

btw: Thanks for the great help!
