### ISSUE TITLE
Props pageLinkOptions, mapPageUrl doesn't seem to work properly

### ISSUE THREAD

**Issue by jedihugo** [janniks/vue-notion#52]
### Issue: `pageLinkOption` and `mapPageUrl` prop doesn't seem to work
- `pageLinkOption`: doesn't change the component to NuxtLink (per inspection still `<a href target=_blank />`)
- `mapPageUrl`: doesn't add `/post` to path before `pageId`
```js
data() {
  return {
    pageLinkOptions: { component: "NuxtLink", href: "to" },
  };
},
methods: {
  mapPageUrl(pageId = "") {
    pageId = pageId.replace(/-/g, "");
    return `/post/${pageId}`;
  }
}
```

### How to reproduce:
- I tested on the nuxt example: `https://github.com/janniks/vue-notion/tree/main/example/pages/_slug.vue`, which already uses `pageLinkOption`. I added methods `mapPageUrl`, and call it in the props:
  ```html
  <template>
    <NotionRenderer
      :blockMap="blockMap"
      :pageLinkOptions="pageLinkOptions"
      :mapPageUrl="mapPageUrl"
      fullPage
      prism
    />
  </template>
  ```
- Also tried on my test pageBlocks that has links and urls: `5c9c85aafc584ba18cdae7eb9e13a27c`
- It doesn't change component to `NuxtLink to`, still `<a href target=_blank />`
- It also doesn't add subpath `/post`

**Comment by janniks** [comment]
Yes, you are right. I found the bugs to fix this. Will release soon

**Comment by janniks** [comment]
Thanks for the detailed error report. The pageId and info really helped!

I believe this is now fixed in `1.2.1` — Please check to see if everything works as expected... ☺️

**Comment by janniks** [comment]
Your example works [here](https://6jhg3.sse.codesandbox.io/5c9c85aafc584ba18cdae7eb9e13a27c) for this [codesandbox](https://codesandbox.io/s/vibrant-satoshi-6jhg3?file=/pages/_slug.vue)

**Comment by jedihugo** [comment]
This is working now as expected. Thank you!
