### ISSUE TITLE
Toggles not working again

### ISSUE THREAD

**Issue by Diferno** [janniks/vue-notion#53]
Gmorning!
Sorry to disturb, but toggles seem to not be rendering content again. Last week when you closed the issue [#50](https://github.com/janniks/vue-notion/issues/50), they were working like a charm, but today.... no content is fetched.

Could you check, pls?

Thx in advance

**Comment by janniks** [comment]
Hmm, very interesting. Can I ask how you are fetching the `blockMap`? Are you specifying a custom URL?

I will check in a couple of hours 👍🏻

**Comment by janniks** [comment]
I redeployed https://vue-notion.vercel.app/ and it still seems to work there…

**Comment by Diferno** [comment]
Hi! thx for the quick answer as always!

This behavior is very odd. In our production environment everything is working again after yesterday, but we created a test project to share with you and it's not working in that one.

It's a clone of the Nuxt project with _slug.vue page
[Link to running project](https://testing.d2vo37bleew6co.amplifyapp.com/) 
[Notion Page](https://www.notion.so/residelia/Testing-Toggle-and-Subpages-f6a54c357fa24a3da9b8ec530a7f1550)

I would like to understand why sometimes the content seem to be fetched and others is not

**Comment by janniks** [comment]
Not sure what this could be. I tried a fresh [example install in Codesandbox](https://codesandbox.io/s/green-bird-uo764) and it seems to work [with your page id](https://uo764.sse.codesandbox.io/f6a54c357fa24a3da9b8ec530a7f1550).

Hard to tell without seeing the exact code. Maybe you're using a different https://github.com/splitbee/notion-api-worker URL...

**Comment by janniks** [comment]
_closing for now_

I also fixed the tab/window opening and page id issues that were shown in your running project in `1.2.0`
