### ISSUE TITLE
Open the gate for custom Vue image component

### ISSUE THREAD

**Issue by eliasparis** [janniks/vue-notion#61]
Hi @janniks , hope you are having a good day.
Thanks for contributing with such a cool lib like **vue-notion**. It really helps to kick up and showcase some ideas that previously will only remain within Notion itself.

I was wondering what do you think about allowing to set different custom components to render the blocks list. I mean, the same way it is possible to set links as ```<NuxtLinks/>``` components, I think it would be very nice and convenient to be posible to set images as, for example, ```<nuxt-image/>``` components, so we benefit of its available optimizations, official docs are [here](https://image.nuxtjs.org/). 

Hope it sounds like a great idea, and thanks one more time for your time and efforts! 🚀

**Comment by janniks** [comment]
Released under [`1.4.0`](https://github.com/janniks/vue-notion/releases/tag/1.4.0) 🚀
