### ISSUE TITLE
Using Vercel--> 404

### ISSUE THREAD

**Issue by mawnir** [janniks/vue-notion#62]
hi, i'm new to this and i'm trying to deploy in Vercel but i only see: "404: NOT_FOUND" 
https://vue-notion-8gmx6yx8s-mawnir.vercel.app/
what i'm doing wrong?

**Comment by janniks** [comment]
Hi, sorry for the delay — it's hard for us to tell what the issue is 😬
To reproduce we would need a codesandbox or similar.
