### ISSUE TITLE
Notions new (simple) tables

### ISSUE THREAD

**Issue by tim-koehler** [janniks/vue-notion#71]
Hey @janniks and others,
notion recently published a new table type. It can be used to create basic simple tables.
https://www.notion.so/guides/simple-tables-vs-databases

Any plans to add that feature also to `vue-notion`? Right know these tables are just not getting rendered.

Thanks a lot for the awesome project! 

\- Tim

**Comment by janniks** [comment]
Hi 🙋🏼‍♂️ 
Could you test if it works with version 1.3.2? A contributor just added some simple table functionality a few days ago.

**Comment by tim-koehler** [comment]
Oh I should have checked the PRs first...It is indeed working with version `1.3.2` 🥳 
The formatting is not perfect but it is good enough 👍🏼 

Thanks again
\- Tim
